name: Upload images to Aliyun OSS

on:
  push:
    paths:
      - "src/img/**"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install OSSCLI 2.1.2
        run: |
          curl -o ossutil-2.1.2-linux-amd64.zip https://gosspublic.alicdn.com/ossutil/v2/2.1.2/ossutil-2.1.2-linux-amd64.zip
          unzip ossutil-2.1.2-linux-amd64.zip
          cd ossutil-2.1.2-linux-amd64
          chmod 755 ossutil
          sudo mv ossutil /usr/local/bin/ && sudo ln -s /usr/local/bin/ossutil /usr/bin/ossutil

      - name: Configure OSSCLI
        env:
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        run: |
          cat > ~/.ossutilconfig <<EOF
          [Credentials]
          language=EN
          endpoint=${OSS_ENDPOINT}
          accessKeySecret=${OSS_ACCESS_KEY_SECRET}
          accessKeyID=${OSS_ACCESS_KEY_ID}
          EOF

      - name: Find added or modified images
        id: find_files
        run: |
          files=$(git diff --name-only --diff-filter=AM HEAD~1 HEAD | grep '^src/img/' || true)
          echo "found files:"
          echo "$files"
          files=$(echo "$files" | tr '\n' ' ')
          echo "FILES=$files" >> $GITHUB_ENV

      - name: Upload images to OSS
        env:
          OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
        run: |
          if [ -z "$FILES" ]; then
            echo "No new or modified images to upload."
            exit 0
          fi

          for file in $FILES; do
            echo "Uploading $file..."
            dest="souta/friend/${file#src/img/}"
            ossutil cp "$file" "oss://${OSS_BUCKET}/${dest}" --update
          done
